### ISSUE TITLE
Image deployment goes into `crashloopbackoff`

### ISSUE THREAD

**Issue by rexagod** [rexagod/base-ubi-nginx#2]
We reckon this is the case because OpenShift requires additional privileges on the image to be able to run it on it's cluster. 

Refer (for pointers): 
* https://catalog.redhat.com/software/containers/ubi8/nginx-118/5f521a6f9dd2d5ca7158e5dc?container-tabs=dockerfile 
* https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/Dockerfile-alpine.template

**Comment by rexagod** [comment]
@weirdwiz Need your acumen here.

**Comment by bipuladh** [comment]
@weirdwiz can we close this issue now?

**Comment by weirdwiz** [comment]
yes, we can close this issue. it is working fine on openshift. no change needed
